// Playlist created by: yaron
// Currently 90 songs
// Always call add_music_profile first to create the profile
add_music_profile(yaron, "yaron's Mix")

add_to_music_profile(yaron, CONGO_JUNGLE)
add_to_music_profile(yaron, DREAM_LAND)
add_to_music_profile(yaron, FINAL_DESTINATION)
add_to_music_profile(yaron, PLANET_ZEBES)
add_to_music_profile(yaron, 7AM)
add_to_music_profile(yaron, AGAVE)
add_to_music_profile(yaron, KOOPA_BROS)
add_to_music_profile(yaron, BABY_BOWSER)
//add_to_music_profile(yaron, BALLOONFIGHT)
//add_to_music_profile(yaron, DANGEROUS_FOE)
add_to_music_profile(yaron, BLOODY_TEARS)
add_to_music_profile(yaron, BLUE_RESORT)
add_to_music_profile(yaron, FZERO_CLIMBUP)
add_to_music_profile(yaron, FF4BOSS)
add_to_music_profile(yaron, NORFAIR)
add_to_music_profile(yaron, POKEMON_CHAMPION)
// banger alert
add_to_music_profile(yaron, CHEMICAL_PLANT)
add_to_music_profile(yaron, CHILL)
add_to_music_profile(yaron, CLOCKTOWER)
add_to_music_profile(yaron, CONTROL)
add_to_music_profile(yaron, CORRIDORS_OF_TIME)
//add_to_music_profile(yaron, DARKWORLD)
// DIRE_DIRE_DOCKS?
//add_to_music_profile(yaron, DOOM1)
add_to_music_profile(yaron, DRACULAS_TEARS)
add_to_music_profile(yaron, EASTON_KINGDOM)
add_to_music_profile(yaron, EMERALDHILL)
add_to_music_profile(yaron, DR_MARIO)
add_to_music_profile(yaron, NIGHTMARE)
add_to_music_profile(yaron, FLYINGBATTERY)
add_to_music_profile(yaron, FORGONE)
add_to_music_profile(yaron, FOREST_INTERLUDE)
add_to_music_profile(yaron, FOURSIDE)
add_to_music_profile(yaron, GAME_CORNER)
add_to_music_profile(yaron, BATTLE_GOLD_SILVER)
add_to_music_profile(yaron, FOD)
add_to_music_profile(yaron, GRABBAG)
add_to_music_profile(yaron, FINALTEMPLE)
add_to_music_profile(yaron, GREEN_HILL_ZONE)
add_to_music_profile(yaron, RBY_GYMLEADER)
add_to_music_profile(yaron, HILLTOPCHASE)
add_to_music_profile(yaron, HORROR_LAND)
add_to_music_profile(yaron, JUNGLEJAPES)
add_to_music_profile(yaron, DEDEDE)
add_to_music_profile(yaron, KIRBY_64_BOSS)
add_to_music_profile(yaron, MEMENTOS)
add_to_music_profile(yaron, FUGUE)
add_to_music_profile(yaron, LIVE_AND_LEARN)
add_to_music_profile(yaron, TOWEROFHEAVEN)
add_to_music_profile(yaron, SOCCER_MENU)
add_to_music_profile(yaron, MK_REVENGE)
add_to_music_profile(yaron, METALLIC_MADNESS)
add_to_music_profile(yaron, MAJORA_MIDBOSS)
add_to_music_profile(yaron, MURASAKI)
add_to_music_profile(yaron, MUTE_CITY)
// banger alert
add_to_music_profile(yaron, NUTTY_NOON)
add_to_music_profile(yaron, BRAWL_OOT)
add_to_music_profile(yaron, OPEN_YOUR_HEART)
add_to_music_profile(yaron, DKCTITLE)
add_to_music_profile(yaron, OPUS_13)
add_to_music_profile(yaron, PLANTATION)
add_to_music_profile(yaron, POLLYANNA)
add_to_music_profile(yaron, PORKY)
add_to_music_profile(yaron, RAIDBLUE)
add_to_music_profile(yaron, RAINBOWROAD)
add_to_music_profile(yaron, POKEFLOATS)
add_to_music_profile(yaron, REDIAL)
add_to_music_profile(yaron, GLACIAL)
add_to_music_profile(yaron, ROCKSOLID)
add_to_music_profile(yaron, ROLL)
add_to_music_profile(yaron, RUNNING_FROM_EVIL)
add_to_music_profile(yaron, SS_AQUA)
add_to_music_profile(yaron, SAMBA_DE_COMBO)
add_to_music_profile(yaron, SHERBETLAND)
add_to_music_profile(yaron, WORLD_OF_ENVY)
add_to_music_profile(yaron, STARDUST)
add_to_music_profile(yaron, STARRING_WARIO)
add_to_music_profile(yaron, STICKERBRUSH_SYMPHONY)
// banger alert
add_to_music_profile(yaron, TALENTSTUDIO)
// banger alert
add_to_music_profile(yaron, THE_DAYS_WHEN_MY_MOTHER_WAS_THERE)
add_to_music_profile(yaron, MORRIGAN)
add_to_music_profile(yaron, CRASH3)
add_to_music_profile(yaron, TOADS_TURNPIKE)
add_to_music_profile(yaron, FIRE_EMBLEM)
add_to_music_profile(yaron, POKEMON_STADIUM)
add_to_music_profile(yaron, SHANTAEMEDLEY)
// banger alert
add_to_music_profile(yaron, TROUBLE_MAKER)
// banger alert
add_to_music_profile(yaron, FLANDRES_THEME)
add_to_music_profile(yaron, UNFOUNDED_REVENGE)
add_to_music_profile(yaron, ZEBES_LANDING)
add_to_music_profile(yaron, VAMPIREKILLER)
//add_to_music_profile(yaron, VSRIDLEY)
add_to_music_profile(yaron, WALUIGI_PINBALL)
add_to_music_profile(yaron, WARIOWARE)
add_to_music_profile(yaron, WILY_FIELD)
add_to_music_profile(yaron, WITHMILASDIVINEPROTECTION)
